<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses =
        [
            ['course_name' => 'Akuntansi 1', 'faculty_id' => 1],
            ['course_name' => 'Akuntansi 2', 'faculty_id' => 1],
            ['course_name' => 'Akuntansi 3', 'faculty_id' => 1],
            ['course_name' => 'Ilmu Ekonomi 1', 'faculty_id' => 1],
            ['course_name' => 'Ilmu Ekonomi 2', 'faculty_id' => 1],
            ['course_name' => 'Ilmu Ekonomi 3', 'faculty_id' => 1],
            ['course_name' => 'Manajemen 1', 'faculty_id' => 1],
            ['course_name' => 'Manajemen 2', 'faculty_id' => 1],
            ['course_name' => 'Manajemen 3', 'faculty_id' => 1],
            
            ['course_name' => 'Administrasi Negara 1', 'faculty_id' => 2],
            ['course_name' => 'Administrasi Negara 2', 'faculty_id' => 2],
            ['course_name' => 'Administrasi Negara 3', 'faculty_id' => 2],
            ['course_name' => 'Ilmu Hukum 1', 'faculty_id' => 2],
            ['course_name' => 'Ilmu Hukum 2', 'faculty_id' => 2],
            ['course_name' => 'Ilmu Hukum 3', 'faculty_id' => 2],

            ['course_name' => 'Kebidanan 1', 'faculty_id' => 3],
            ['course_name' => 'Kebidanan 2', 'faculty_id' => 3],
            ['course_name' => 'Kebidanan 3', 'faculty_id' => 3],
            ['course_name' => 'Kedokteran Hewan 1', 'faculty_id' => 3],
            ['course_name' => 'Kedokteran Hewan 2', 'faculty_id' => 3],
            ['course_name' => 'Kedokteran Hewan 3', 'faculty_id' => 3],
            ['course_name' => 'Psikologi 1', 'faculty_id' => 3],
            ['course_name' => 'Psikologi 2', 'faculty_id' => 3],
            ['course_name' => 'Psikologi 3', 'faculty_id' => 3],
            ['course_name' => 'Pendidikan Dokter 1', 'faculty_id' => 3],
            ['course_name' => 'Pendidikan Dokter 2', 'faculty_id' => 3],
            ['course_name' => 'Pendidikan Dokter 3', 'faculty_id' => 3],
            
            ['course_name' => 'Teknik Arsitektur 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Arsitektur 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Arsitektur 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Elektro 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Elektro 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Elektro 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Geologi 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Geologi 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Industri 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Industri 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Industri 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Informatika 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Informatika 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Informatika 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Kelautan 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Kelautan 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Kelautan 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Lingkungan 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Lingkungan 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Lingkungan 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Mesin 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Mesin 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Mesin 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Perkapalan 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Perkapalan 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Perkapalan 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Pertambangan 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Pertambangan 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Pertambangan 3', 'faculty_id' => 4],
            ['course_name' => 'Teknik Perencanaan Wilayah dan Kota 1', 'faculty_id' => 4],
            ['course_name' => 'Teknik Perencanaan Wilayah dan Kota 2', 'faculty_id' => 4],
            ['course_name' => 'Teknik Perencanaan Wilayah dan Kota 3', 'faculty_id' => 4],
            
            ['course_name' => 'Antropologi 1', 'faculty_id' => 5],
            ['course_name' => 'Antropologi 2', 'faculty_id' => 5],
            ['course_name' => 'Antropologi 3', 'faculty_id' => 5],
            ['course_name' => 'Hubungan Internasional 1', 'faculty_id' => 5],
            ['course_name' => 'Hubungan Internasional 2', 'faculty_id' => 5],
            ['course_name' => 'Hubungan Internasional 3', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Administrasi 1', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Administrasi 2', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Administrasi 3', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Komunikasi 1', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Komunikasi 2', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Komunikasi 3', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Pemerintahan 1', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Pemerintahan 2', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Pemerintahan 3', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Politik 1', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Politik 2', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Politik 3', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Sosiologi 1', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Sosiologi 2', 'faculty_id' => 5],
            ['course_name' => 'Ilmu Sosiologi 3', 'faculty_id' => 5],
            
            ['course_name' => 'Arkeologi 1', 'faculty_id' => 6],
            ['course_name' => 'Arkeologi 2', 'faculty_id' => 6],
            ['course_name' => 'Arkeologi 3', 'faculty_id' => 6],
            ['course_name' => 'Sejarah 1', 'faculty_id' => 6],
            ['course_name' => 'Sejarah 2', 'faculty_id' => 6],
            ['course_name' => 'Sejarah 3', 'faculty_id' => 6],
            ['course_name' => 'Sastra Arab 1', 'faculty_id' => 6],
            ['course_name' => 'Sastra Arab 2', 'faculty_id' => 6],
            ['course_name' => 'Sastra Arab 3', 'faculty_id' => 6],
            ['course_name' => 'Sastra Indonesia 1', 'faculty_id' => 6],
            ['course_name' => 'Sastra Indonesia 2', 'faculty_id' => 6],
            ['course_name' => 'Sastra Indonesia 3', 'faculty_id' => 6],
            ['course_name' => 'Sastra Inggris 1', 'faculty_id' => 6],
            ['course_name' => 'Sastra Inggris 2', 'faculty_id' => 6],
            ['course_name' => 'Sastra Inggris 3', 'faculty_id' => 6],
            ['course_name' => 'Sastra Jepang 1', 'faculty_id' => 6],
            ['course_name' => 'Sastra Jepang 2', 'faculty_id' => 6],
            ['course_name' => 'Sastra Jepang 3', 'faculty_id' => 6],
            ['course_name' => 'Sastra & Bahasa Asing 1', 'faculty_id' => 6],
            ['course_name' => 'Sastra & Bahasa Asing 2', 'faculty_id' => 6],
            ['course_name' => 'Sastra & Bahasa Asing 3', 'faculty_id' => 6],
            ['course_name' => 'Sastra & Bahasa Daerah 1', 'faculty_id' => 6],
            ['course_name' => 'Sastra & Bahasa Daerah 2', 'faculty_id' => 6],
            ['course_name' => 'Sastra & Bahasa Daerah 3', 'faculty_id' => 6],
            
            ['course_name' => 'Agribisnis 1', 'faculty_id' => 7],
            ['course_name' => 'Agribisnis 2', 'faculty_id' => 7],
            ['course_name' => 'Agribisnis 3', 'faculty_id' => 7],
            ['course_name' => 'Agroteknologi 1', 'faculty_id' => 7],
            ['course_name' => 'Agroteknologi 2', 'faculty_id' => 7],
            ['course_name' => 'Agroteknologi 3', 'faculty_id' => 7],
            ['course_name' => 'Ilmu dan Teknologi Pangan 1', 'faculty_id' => 7],
            ['course_name' => 'Ilmu dan Teknologi Pangan 2', 'faculty_id' => 7],
            ['course_name' => 'Ilmu dan Teknologi Pangan 3', 'faculty_id' => 7],
            
            ['course_name' => 'Aktuaria 1', 'faculty_id' => 8],
            ['course_name' => 'Aktuaria 2', 'faculty_id' => 8],
            ['course_name' => 'Aktuaria 3', 'faculty_id' => 8],
            ['course_name' => 'Biologi 1', 'faculty_id' => 8],
            ['course_name' => 'Biologi 2', 'faculty_id' => 8],
            ['course_name' => 'Biologi 3', 'faculty_id' => 8],
            ['course_name' => 'Fisika 1', 'faculty_id' => 8],
            ['course_name' => 'Fisika 2', 'faculty_id' => 8],
            ['course_name' => 'Fisika 3', 'faculty_id' => 8],
            ['course_name' => 'Geofisika 1', 'faculty_id' => 8],
            ['course_name' => 'Geofisika 2', 'faculty_id' => 8],
            ['course_name' => 'Geofisika 3', 'faculty_id' => 8],
            ['course_name' => 'Kimia 1', 'faculty_id' => 8],
            ['course_name' => 'Kimia 2', 'faculty_id' => 8],
            ['course_name' => 'Kimia 3', 'faculty_id' => 8],
            ['course_name' => 'Matematika 1', 'faculty_id' => 8],
            ['course_name' => 'Matematika 2', 'faculty_id' => 8],
            ['course_name' => 'Matematika 3', 'faculty_id' => 8],
            ['course_name' => 'Statistika 1', 'faculty_id' => 8],
            ['course_name' => 'Statistika 2', 'faculty_id' => 8],
            ['course_name' => 'Statistika 3', 'faculty_id' => 8],
            ['course_name' => 'Sistem Informasi 1', 'faculty_id' => 8],
            ['course_name' => 'Sistem Informasi 2', 'faculty_id' => 8],
            ['course_name' => 'Sistem Informasi 3', 'faculty_id' => 8],
            
            ['course_name' => 'Peternakan 1', 'faculty_id' => 9],
            ['course_name' => 'Peternakan 2', 'faculty_id' => 9],
            ['course_name' => 'Peternakan 3', 'faculty_id' => 9],

            ['course_name' => 'Pendidikan Kedokteran Gigi 1', 'faculty_id' => 10],
            ['course_name' => 'Pendidikan Kedokteran Gigi 2', 'faculty_id' => 10],
            ['course_name' => 'Pendidikan Kedokteran Gigi 3', 'faculty_id' => 10],
            
            ['course_name' => 'Ilmu Gizi 1', 'faculty_id' => 11],
            ['course_name' => 'Ilmu Gizi 2', 'faculty_id' => 11],
            ['course_name' => 'Ilmu Gizi 3', 'faculty_id' => 11],
            ['course_name' => 'Kesehatan Masyarakat 1', 'faculty_id' => 11],
            ['course_name' => 'Kesehatan Masyarakat 2', 'faculty_id' => 11],
            ['course_name' => 'Kesehatan Masyarakat 3', 'faculty_id' => 11],

            ['course_name' => 'Budidaya Perairan (Akuakultur) 1', 'faculty_id' => 12],
            ['course_name' => 'Budidaya Perairan (Akuakultur) 2', 'faculty_id' => 12],
            ['course_name' => 'Budidaya Perairan (Akuakultur) 3', 'faculty_id' => 12],
            ['course_name' => 'Ilmu Kelautan 1', 'faculty_id' => 12],
            ['course_name' => 'Ilmu Kelautan 2', 'faculty_id' => 12],
            ['course_name' => 'Ilmu Kelautan 3', 'faculty_id' => 12],
            ['course_name' => 'Manajemen Sumber Daya Perairan 1', 'faculty_id' => 12],
            ['course_name' => 'Manajemen Sumber Daya Perairan 2', 'faculty_id' => 12],
            ['course_name' => 'Manajemen Sumber Daya Perairan 3', 'faculty_id' => 12],
            ['course_name' => 'Perikanan 1', 'faculty_id' => 12],
            ['course_name' => 'Perikanan 2', 'faculty_id' => 12],
            ['course_name' => 'Perikanan 3', 'faculty_id' => 12],

            ['course_name' => 'Kehutanan 1', 'faculty_id' => 13],
            ['course_name' => 'Kehutanan 2', 'faculty_id' => 13],
            ['course_name' => 'Kehutanan 3', 'faculty_id' => 13],

            ['course_name' => 'Farmasi 1', 'faculty_id' => 14],
            ['course_name' => 'Farmasi 2', 'faculty_id' => 14],
            ['course_name' => 'Farmasi 3', 'faculty_id' => 14],
            
            ['course_name' => 'Fisioterapi 1', 'faculty_id' => 15],
            ['course_name' => 'Fisioterapi 2', 'faculty_id' => 15],
            ['course_name' => 'Fisioterapi 3', 'faculty_id' => 15],
            ['course_name' => 'Ilmu Keperawatan 1', 'faculty_id' => 15],
            ['course_name' => 'Ilmu Keperawatan 2', 'faculty_id' => 15],
            ['course_name' => 'Ilmu Keperawatan 3', 'faculty_id' => 15],

            ['course_name' => 'Vokasi 1', 'faculty_id' => 16],
            ['course_name' => 'Vokasi 2', 'faculty_id' => 16],
            ['course_name' => 'Vokasi 3', 'faculty_id' => 16],
        ];

        foreach($courses as $course){
            Course::create($course);
        }
    }
}
